#include "holberton.h"

int main(void)
{
	int alen, elen;

/*	int p = 237482;
        int n = -328472;
        int z = 0;
*/	char c = 'z';
	char *str = NULL;
	unsigned int ui;
/*	void *addr;

	addr = (void *)0x7ffe637541f0;
*/	ui = (unsigned int)INT_MAX + 1024;
	/*	printf(NULL); */
	_printf(NULL);
	printf("START OF TEST\n");

	printf("=====================\n");
/*	printf("printf(NULL)  : %d\n", printf(str));
	printf("_printf(NULL) : %d\n", _printf(str));
	printf("printf(\"%\") : %d\n", printf("%"));
	printf("_printf(\"%\"): %d\n", _printf("%"));
*/	str = "hello, world";
	printf("=====================\n");
	printf("*****CHAR*****\n");
	printf("=====================\n");
	printf("Expected   : %c\n", 'a');
	_printf("Actual     : %c\n", 'a');
	elen = printf("Expected   : %c\n", c);
	alen = _printf("Actual     : %c\n", c);
	printf("Expected   : %i\n", elen);
	printf("Actual     : %i\n", alen);
	printf("Expected   : %cc\n", 'a');
	_printf("Actual     : %cc\n", 'a');
	printf("Expected   : %c\n", 53);
	_printf("Actual     : %c\n", 53);
	printf("Expected   : %c.\n", '\0');
	_printf("Actual     : %c.\n", '\0');
	printf("Expected   : %%%c\n", 'y');
	_printf("Actual     : %%%c\n", 'y');
	printf("=====================\n");
	printf("*****STRINGS*****\n");
	printf("=====================\n");
	alen = elen = 0;
	printf("Expected   : %s\n", "holberton");
	_printf("Actual     : %s\n", "holberton");
	printf("Expected   : %s$\n", "");
	_printf("Actual     : %s$\n", "");
	elen = printf("Expected   : %s\n", str);
	alen = _printf("Actual     : %s\n", str);
	elen = printf("%s", "");
	alen = _printf("%s", "");
	printf("Expected   : %i\n", elen);
	printf("Actual     : %i\n", alen);
	printf("Expected   : %sschool\n", "holberton");
	_printf("Actual     : %sschool\n", "holberton");
/*	elen = printf("Expected: %c%%%c%%%%%s%c%s%s\n", INT_MAX, INT_MIN, "hello", 0, "holberton", 0);
	alen = _printf("Actual  : %c%%%c%%%%%s%c%s%s\n", INT_MAX, INT_MIN, "hello", 0, "holberton", 0);
*/	printf("Expected: %d\n", elen);
	printf("Actual  : %d\n", alen);
	printf("Expected  %i %d\n", 0032, 0032);
        _printf("Actual %i %d \n", 0032, 0032);

/**	printf("=====================\n");
	printf("*****INTEGER*****\n");
	printf("=====================\n");
	alen = elen = 0;
	elen = printf("Expected   : %i %i\n", p, p);
	alen = _printf("Actual     : %i %i\n", p, p);
	printf("Expected   : %i\n", elen);
	_printf("Actual     : %i\n", alen);
	elen = printf("Expected   : %i\n", n);
	alen = _printf("Actual     : %i\n", n);
	printf("Expected   : %i\n", elen);
	_printf("Actual     : %i\n", alen);
	elen = printf("Expected   : %i\n", z);
	alen = _printf("Actual     : %i\n", z);
	printf("Expected   : %i\n", elen);
	_printf("Actual     : %i\n", alen);
	printf("Expected   : %i\n", INT_MAX);
	_printf("Actual     : %i\n", INT_MAX);
	printf("Expected   : %i\n", INT_MIN);
	_printf("Actual     : %i\n", INT_MIN);

		printf("=====================\n");
		printf("*****DECIMAL*****\n");
	printf("=====================\n");
	alen = elen = 0;
	p = 1134001;
	n = -4567;
	z = 0;
	elen = printf("Expected   : %d\n", p);
	alen = _printf("Actual     : %d\n", p);
	printf("Expected   : %d\n", elen);
	_printf("Actual     : %d\n", alen);
	elen = printf("Expected   : %d\n", n);
	alen = _printf("Actual     : %d\n", n);
	printf("Expected   : %d\n", elen);
	_printf("Actual     : %d\n", alen);
	elen = printf("Expected   : %i\n", z);
	alen = _printf("Actual     : %i\n", z);
	printf("Expected   : %i\n", elen);
	_printf("Actual     : %i\n", alen);
	printf("a = %i, b = %i, c = %i\n", 12, 012, 0x12);
	_printf("a = %i, b = %i, c = %i\n", 12, 012, 0x12);
	printf("Expected   : %d\n", 2147483647);
	_printf("Actual     : %d\n", 2147483647);
	printf("Expected   : %d\n", -2147483648);
	_printf("Actual     : %d\n", INT_MIN);
*/	printf("=====================\n");
	printf("*****BINARY*****\n");
	printf("=====================\n");
	elen = _printf("%b\n", 98);
	printf("Expected   : 7\n");
	_printf("Actual     : %d\n", elen);
	_printf("Actual     : %b\n");
	printf("=====================\n");
	printf("*****HEXADECIMAL*****\n");
	printf("=====================\n");
	_printf("Unsigned hexadecimal:[%x, %X]\n", ui, ui);
	printf("Unsigned hexadecimal:[%x, %X]\n", ui, ui);
	printf("=====================\n");
	printf("*****OCTAL*****\n");
	printf("=====================\n");
	_printf("Unsigned octal:[%o]\n", ui);
	printf("Unsigned octal:[%o]\n", ui);
/*	_printf("Address:[%p]\n", addr);
	printf("Address:[%p]\n", addr);
*/
	printf("=====================\n");
	printf("*****FLAGS*****\n");
	printf("=====================\n");
	printf("Expected   : %+5.5s\n", "holberton");
	_printf("Actual     : %12.2400d\n", 2143);
	printf("Expected   : %d\n", 2143);
	_printf("Actual     : %+d\n", 2143);
	printf("Expected   : %+d\n", -2143);
	_printf("Actual     : %+d\n", -2143);
	printf("Expected   : % d\n", 2143);
	_printf("Actual     : % d\n", 2143);
	printf("Expected   : % d\n", -2143);
	_printf("Actual     : % d\n", -2143);
	printf("Unsigned octal:[%#o]\n", ui);
	_printf("Unsigned octal:[%#o]\n", ui);
	printf("Unsigned hexadecimal:[%#x, %#X]\n", ui, ui);
	_printf("Unsigned hexadecimal:[%#x, %#X]\n", ui, ui);
	printf("Expected   : %19s\n", "holberton");
	_printf("Actual     : %+s\n", "holberton");

	return (0);
}
